const SecondPage = () => {
  return ` 
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra ipsum nunc aliquet bibendum enim. Sed felis eget velit aliquet sagittis id consectetur purus. Lacinia at quis risus sed vulputate odio. Tristique senectus et netus et malesuada fames ac turpis. Vitae congue eu consequat ac felis donec et odio pellentesque. Purus gravida quis blandit turpis cursus in hac habitasse. Nunc sed id semper risus in hendrerit gravida rutrum. Diam in arcu cursus euismod quis viverra. Suspendisse ultrices gravida dictum fusce ut placerat. Lorem mollis aliquam ut porttitor leo a diam. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Nec feugiat in fermentum posuere.
Fringilla ut morbi tincidunt augue. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Viverra nibh cras pulvinar mattis nunc sed blandit. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sed arcu non odio euismod. In est ante in nibh mauris cursus mattis molestie a. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Nulla facilisi etiam dignissim diam. Sed tempus urna et pharetra. Congue quisque egestas diam in arcu cursus euismod quis viverra. Mattis vulputate enim nulla aliquet. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Tortor at risus viverra adipiscing at. Quis risus sed vulputate odio ut enim blandit volutpat maecenas.
Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aenean et tortor at risus. Ipsum a arcu cursus vitae congue mauris rhoncus. Aenean et tortor at risus viverra adipiscing at in. Nunc sed id semper risus in hendrerit. Neque vitae tempus quam pellentesque nec nam aliquam. Odio pellentesque diam volutpat commodo sed. Aliquet nec ullamcorper sit amet risus nullam eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Amet luctus venenatis lectus magna. Netus et malesuada fames ac turpis egestas sed.
Eget nunc lobortis mattis aliquam faucibus purus in. Aenean sed adipiscing diam donec adipiscing tristique. Sit amet commodo nulla facilisi nullam vehicula ipsum. Ipsum faucibus vitae aliquet nec. Cras adipiscing enim eu turpis egestas pretium. Ligula ullamcorper malesuada proin libero nunc. Bibendum est ultricies integer quis auctor elit sed. Ut placerat orci nulla pellentesque dignissim enim sit amet. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Sem nulla pharetra diam sit amet nisl. Elit ut aliquam purus sit. Eu volutpat odio facilisis mauris sit amet. Lectus nulla at volutpat diam ut venenatis. Sit amet venenatis urna cursus eget nunc. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel.
Dolor sit amet consectetur adipiscing elit. Diam ut venenatis tellus in metus vulputate eu scelerisque. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Turpis cursus in hac habitasse platea. Vitae ultricies leo integer malesuada nunc. Et netus et malesuada fames ac turpis egestas. Quis imperdiet massa tincidunt nunc. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Sem integer vitae justo eget magna fermentum iaculis. Morbi tempus iaculis urna id volutpat. Etiam erat velit scelerisque in. Neque sodales ut etiam sit amet nisl purus in. In cursus turpis massa tincidunt dui ut ornare lectus sit. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Maecenas sed enim ut sem viverra aliquet eget. Turpis nunc eget lorem dolor sed. Urna molestie at elementum eu.
Et egestas quis ipsum suspendisse ultrices. Justo nec ultrices dui sapien eget mi. Dolor purus non enim praesent elementum. Erat imperdiet sed euismod nisi porta lorem mollis. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Ut etiam sit amet nisl. Eget aliquet nibh praesent tristique magna sit. Egestas quis ipsum suspendisse ultrices gravida dictum. Elementum integer enim neque volutpat. Nunc sed velit dignissim sodales ut. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Urna nunc id cursus metus. Ipsum nunc aliquet bibendum enim facilisis gravida neque.
Tortor at auctor urna nunc id cursus metus. Purus in massa tempor nec feugiat nisl. Feugiat nibh sed pulvinar proin. In pellentesque massa placerat duis ultricies. Sem fringilla ut morbi tincidunt augue interdum velit. Vestibulum rhoncus est pellentesque elit ullamcorper. Malesuada fames ac turpis egestas integer eget aliquet nibh. Volutpat ac tincidunt vitae semper quis. Accumsan lacus vel facilisis volutpat est velit egestas dui. Eros donec ac odio tempor orci. Id diam maecenas ultricies mi eget mauris. Sit amet mattis vulputate enim nulla. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Bibendum neque egestas congue quisque egestas diam in. Feugiat in fermentum posuere urna. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.
Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Donec et odio pellentesque diam volutpat commodo sed. Imperdiet dui accumsan sit amet. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Mauris ultrices eros in cursus turpis massa tincidunt. Venenatis tellus in metus vulputate. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Ut sem nulla pharetra diam sit amet nisl suscipit. Nisl vel pretium lectus quam id leo in vitae turpis. Aliquet enim tortor at auctor. Posuere lorem ipsum dolor sit. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Risus viverra adipiscing at in tellus integer feugiat. At consectetur lorem donec massa sapien faucibus et molestie. Sed libero enim sed faucibus turpis in eu mi bibendum. Sed odio morbi quis commodo odio aenean. Odio eu feugiat pretium nibh ipsum consequat.
Massa tincidunt nunc pulvinar sapien et ligula. Adipiscing bibendum est ultricies integer quis auctor. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Eleifend quam adipiscing vitae proin sagittis. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Aliquam faucibus purus in massa tempor. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Blandit massa enim nec dui nunc mattis enim. Arcu risus quis varius quam quisque. Aenean vel elit scelerisque mauris pellentesque. Risus ultricies tristique nulla aliquet enim. A diam maecenas sed enim ut sem viverra aliquet eget. Praesent semper feugiat nibh sed pulvinar proin. Etiam tempor orci eu lobortis elementum. Lectus quam id leo in.
Feugiat sed lectus vestibulum mattis ullamcorper. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Pulvinar sapien et ligula ullamcorper malesuada proin. Volutpat odio facilisis mauris sit amet massa vitae. Augue ut lectus arcu bibendum at varius. Ornare lectus sit amet est. Eu consequat ac felis donec et odio. Sem viverra aliquet eget sit amet tellus. Orci sagittis eu volutpat odio. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Tristique senectus et netus et malesuada fames ac. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Leo in vitae turpis massa sed elementum tempus. Morbi leo urna molestie at elementum eu. Morbi tristique senectus et netus et. Bibendum neque egestas congue quisque egestas. Tempus iaculis urna id volutpat lacus. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius.
Tortor at risus viverra adipiscing at in tellus integer. Dignissim suspendisse in est ante in nibh mauris. In mollis nunc sed id. Tellus cras adipiscing enim eu. Vitae turpis massa sed elementum tempus egestas. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Morbi tristique senectus et netus et malesuada fames ac. Amet consectetur adipiscing elit duis. In arcu cursus euismod quis viverra nibh. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Cursus metus aliquam eleifend mi. Non odio euismod lacinia at quis risus sed vulputate odio. Ut enim blandit volutpat maecenas. Consectetur a erat nam at lectus urna duis convallis convallis.
Nullam eget felis eget nunc lobortis. Mauris vitae ultricies leo integer malesuada nunc vel risus. Suspendisse sed nisi lacus sed viverra tellus in. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Consequat nisl vel pretium lectus quam. Neque ornare aenean euismod elementum nisi. Ultricies mi quis hendrerit dolor magna eget. Platea dictumst vestibulum rhoncus est pellentesque elit. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Est ullamcorper eget nulla facilisi etiam dignissim. Mattis rhoncus urna neque viverra justo nec.
Vitae sapien pellentesque habitant morbi tristique senectus et. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Urna id volutpat lacus laoreet non curabitur. Nunc sed id semper risus in hendrerit gravida. Vulputate dignissim suspendisse in est. Massa sapien faucibus et molestie ac feugiat. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Tincidunt praesent semper feugiat nibh sed pulvinar. A iaculis at erat pellentesque adipiscing commodo. Vitae congue mauris rhoncus aenean vel elit. Duis ut diam quam nulla. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Quisque non tellus orci ac auctor. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Suscipit adipiscing bibendum est ultricies integer quis auctor elit. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Feugiat nisl pretium fusce id velit ut tortor pretium.
Venenatis urna cursus eget nunc. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Gravida rutrum quisque non tellus orci ac auctor. Amet consectetur adipiscing elit pellentesque. Ipsum suspendisse ultrices gravida dictum fusce ut. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Posuere ac ut consequat semper. Odio pellentesque diam volutpat commodo sed. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel.
Morbi tincidunt ornare massa eget egestas purus viverra accumsan. Ultrices gravida dictum fusce ut. Augue lacus viverra vitae congue. Lacus sed turpis tincidunt id aliquet. Hendrerit gravida rutrum quisque non tellus. Arcu cursus vitae congue mauris rhoncus. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Feugiat vivamus at augue eget arcu dictum varius duis. Elit eget gravida cum sociis natoque penatibus. Lectus urna duis convallis convallis tellus id interdum velit. Adipiscing diam donec adipiscing tristique. Vel pharetra vel turpis nunc eget. Est ultricies integer quis auctor elit sed vulputate mi. Tellus rutrum tellus pellentesque eu. Vulputate dignissim suspendisse in est ante in nibh. Cras adipiscing enim eu turpis egestas pretium aenean. Egestas purus viverra accumsan in.
</body>
</html>
`;
};

module.exports = SecondPage;
